---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-206-acc
  labels:
    heritage: example-206
---
# Create and update ValidatingWebhookConfiguration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-206
  labels:
    heritage: example-206
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "list", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-206
  labels:
    heritage: example-206
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-206
subjects:
  - kind: ServiceAccount
    name: example-206-acc
    namespace: {{ .Release.Namespace }}
