[book]
authors = ["The Shell-Operator Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "Shell-operator"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/flant/shell-operator"
